scene: scene_0129
inherit_from: configs/GraspNet/graspnet.yaml
config_path: configs/GraspNet/baseline_random_nbv/scene_0129.yaml
data:
  input_folder: /data/graspnet/scenes/scene_0129/realsense
  output: /data/graspnet/output/GraspNet/baseline_random_nbv/scene_0129_nbv/
mapping:
  keyframe_every: 1
  mesh_freq: 1
  vis_freq: 100
  vis_inside_freq: 100
  iters_first: 150
  iters: 50
  ckpt_freq: 1
  no_log_on_first_frame: false
  random_nbv: true
rendering:
  n_stratified: 32
  n_importance: 8
model:
  grasp_output: online
